const GET_BOOKS = 'GET_BOOKS';
const SET_BOOKS = 'SET_BOOKS';
const GET_FAVORITE_BOOK = 'GET_FAVORITE_BOOK';
const SET_FAVORITE_BOOK = 'SET_FAVORITE_BOOK';
const DELETE_FAVORITE_BOOK = 'DELETE_FAVORITE_BOOK';

export default {
    GET_BOOKS,
    SET_BOOKS,
    GET_FAVORITE_BOOK,
    DELETE_FAVORITE_BOOK,
    SET_FAVORITE_BOOK
}