const SING_IN_USER = "SIGN_IN_USER";
const REGISTRATION_USER = "REGISTRATION_USER";
const SET_IS_AUTH = "SET_IS_AUTH";
const LOGOUT = "LOGOUT";
const UPLOAD_PHOTO = "UPLOAD_PHOTO";
const ADD_POINTS = "ADD_POINTS";
const CHANGE_LEVEL = "CHANGE_LEVEL";
const EDIT = "EDIT";

export default {
    SING_IN_USER,
    REGISTRATION_USER,
    SET_IS_AUTH,
    LOGOUT,
    UPLOAD_PHOTO,
    ADD_POINTS,
    CHANGE_LEVEL,
    EDIT
}